### ISSUE TITLE
problems with firewalld

### ISSUE THREAD

**Issue by dydx** [TalkingQuickly/rails-server-template#37] opened 2015-10-05 23:17 UTC
I can't make heads from tails on this; I'm trying to set this up on an Ubuntu DO droplet, and I've gotten up to the point where you run `bundle exec knife solo root@<ipaddress>`, which promptly fails due to something wrong with Firewalld.

Here is my terminal output: https://gist.github.com/dydx/b0f2bc94a28a9d295a3a

From the looks of it, I don't understand why that part of the setup is even running-- it references RHEL and Fedora, which I am not running.

**Comment by TalkingQuickly** [comment] 2015-10-11 10:32
Could you let me know Ubuntu Version and VPS Provider? The repo is automatically tested every two weeks against Linode and Digital Ocean with  Ubuntu 14.04 (the current LTS) and can't see any failures there. Happy to try and reproduce if you can provide more info though!

**Comment by dydx** [comment] 2015-10-15 07:10
I can't really explain what happened, but I was set to try this provisioning again to try and reproduce it on another day, and it didn't do it-- it actually ran all the way through successfully.

For your information, though, I was running Ubuntu 14.04 on Digital Ocean with a 512Mb/20Gb droplet.

**Comment by zhiyao** [comment] 2015-11-02 07:37
I was facing this issue and have work around a fix. 

From what I understood was that the ufw cookbook required another [firewall](https://github.com/chef-cookbooks/firewall) cookbook. However the latest [firewall](https://github.com/chef-cookbooks/firewall) cookbook is running a new method that is only available in Chef 12.4.x. 

To resolve this issue, I had to add another line `cookbook 'firewall', '1.6.2'` to the berksfile and run `berks install` to lock the firewall cookbook to the previous version so that it would be compatible with Chef 11.6.4 as stated in this project `Gemfile`

**Comment by kernelsmith** [comment] 2016-02-05 22:26
yeah, this is still a problem, according to the ufw readme.md https://github.com/chef-cookbooks/ufw#chef it currently only supports chef 12+ however the Gemfile in here pins chef to:

**Comment by kernelsmith** [comment] 2016-02-05 22:29
I'm gonna unpin chef-client, but if that doesn't work, I'm going to try @zhiyao's solution.  Is there anything holding this template back from using chef 12+?

**Comment by kernelsmith** [comment] 2016-02-05 22:31
@TalkingQuickly my details:

* would-be-rails-server: Ubuntu 14.04.3 LTS

**Comment by TalkingQuickly** [comment] 2016-02-05 23:03
Looking into further now but the version of ufw should also be pinned so it
should be using a version which doesn't require v12?

On Friday, 5 February 2016, Josh <notifications@github.com> wrote:

> @TalkingQuickly <https://github.com/TalkingQuickly> my details:
>
>    - would-be-rails-server: Ubuntu 14.04.3 LTS
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TalkingQuickly/rails-server-template/issues/37#issuecomment-180600238>
> .
>


-- 
-- 

*Ben Dixon*

+44 (0)2 032 894 803
+44 (0)7 762 845 249
http://www.twitter.com/TalkingQuickly
http://www.talkingquickly.co.uk

Dxnx Ltd Trading as Hills Bede
UK Registered Company Number: 6751002

Registered Address:
DXNX LTD
Techhub @ Google Campus
4 - 5 Bonhill Street
London
EC2A 4BX

**Comment by kernelsmith** [comment] 2016-02-05 23:36
I admit I suck at figuring it out, so I may leave it to the professional :)  I'm also thinking chef-solo-search is what may ultimately force chef-client to by 11.?  In my case I believe I can remove chef-solo-search due to use of chef server, but not sure what that might explode yet

**Comment by kernelsmith** [comment] 2016-02-12 23:53
so I found the reason chef-client 11.x was getting installed, ruby pathing issues on the workstation I was using.  Switching to workstation w/a good chefdk installed (and no rvm), I get chef-client 12.x installed and that satisfies firewalld

**Comment by kernelsmith** [comment] 2016-02-17 02:50
so, here's what I had to do to clear this out.  delete all firewall and ufw cookbooks from my chef server, remove all references of ufw and firewall from the Berksfile.lock (so berks would pick up the latest versions), run bersk install to download those latest version, then push them to the chef server.  In addition, nothing seems to ensure recipe[firewall::default] is loaded before ufw is run, so you have to add that the front of the node's runlist

**Comment by kernelsmith** [comment] 2016-02-17 02:52
@TalkingQuickly I can pull request this change if you'd like.  I believe it would only change the Berksfile.lock and add the `recipe[firewall::default]` to the front of the run_list in the node's json file

**Comment by kernelsmith** [comment] 2016-02-17 03:01
I see many sources that say you should never check your gemfile.lock into the repo.  I'm assuming the same reasoning applies to Berskfile.lock files as well.  Granted, I know there is more than one opinion on this matter, however not checking it in would reveal these problems right away and the berksfile itself could be used to constrain the versions if a true incompatibility arises.

**Comment by TalkingQuickly** [comment] 2016-02-17 13:37
Interesting stuff. I think it might be slightly more involved than that. At
the moment the repo includes a Gemfile and is specifically only designed to
work with Chef client 11 (the Gemfile locks it to this). This was
originally due to instability in v12 but agree it probably makes sense to
re-visit this now.

Re the lockfile, with Gemfiles, I think the best practices are:

* If you're not writing a gem, Gemfile.lock should always be checked in.
This is the snapshot of all dependencies, including dependencies of
dependencies which are not captured by the Gemfile
* The only scenario where you should not check in the Gemfile.lock is when
writing a gem

I think the same applies here, it's essential to check in the
Berksfile.lock because it ensures that not only dependencies, but
dependencies of dependencies are correct.

-- 

*Ben Dixon*

+44 (0)2 032 894 803
+44 (0)7 762 845 249
http://www.twitter.com/TalkingQuickly
http://www.talkingquickly.co.uk

Dxnx Ltd Trading as Hills Bede
UK Registered Company Number: 6751002

Registered Address:
DXNX LTD
Techhub @ Google Campus
4 - 5 Bonhill Street
London
EC2A 4BX

**Comment by kernelsmith** [comment] 2016-02-17 17:19
ah, thanks very much for the inside @TalkingQuickly.  I'm pretty new to berks and tho I've done a lot of ruby, I haven't cut many gems.  I can share what I've done to update all cookbooks to latest (except chef-solo-search as I'm not using it) and mysql which needs to remain on 5.x until a wrapper cookbook is either written or snagged from elsewhere.

**Comment by kernelsmith** [comment] 2016-02-17 17:34
Berskfile and .lock: https://gist.github.com/kernelsmith/20c82398bd0065e59830

**Comment by kernelsmith** [comment] 2016-02-18 15:48
oh, I think rbenv changed to ruby_rbenv too, however the attributes remain keyed as "rbenv" vs "ruby_rbenv"

**Comment by TalkingQuickly** [comment] 2017-01-15 12:13
Should be resolved by v4.0 of sample code (along with v4.0.0 of the book), thanks for all the troubleshooting here!

**Closed by TalkingQuickly** 2017-01-15 12:13 UTC

**Comment by kernelsmith** [comment] 2017-01-16 06:31
np, thanks for writing this.  
BTW, you may be have already seen this, but you may be interested in, https://github.com/poise/application_ruby/ pretty clean, might make your life easier (or not given how much work you've already put in)

**Comment by TalkingQuickly** [comment] 2017-01-16 10:02
No that's very cool! I've never looked at using Chef for deployment so would be a fun one to play with, I'll have a go!
